### ISSUE TITLE
Большое финальное задание

### ISSUE THREAD

**Issue by madvlaydin** [leemuar/silverb-devops1-final#1]
**Формирование окружения разработчика**
- [x] Внешние отчеты и обработки разбираются на исходники
- [x] Структура каталогов репозитория из bootstrap

**Формирование описания разработки**
- [x] Коммиты с доступным описанием
- [ ] Коммиты привязаны к issue

**Разработка по промышленным стандартам**
- [x] Одна функциональность = одна фича и сценарии, проверяющие работу этой фичи/функциональности
- [x] Использование фикстур
- [x] Повторное использование шагов (собственная библиотека шагов)

**В дополнение к проверке навыка "Повторное использование шагов (собственная библиотека шагов)"**

Для подтверждения этого навыка у вас должно быть:
1. Две фичи, проверяющие поступление и продажу товара.
2. В каталоге features каталог, в котором вы будете хранить ваши библиотечные фичи.
3. В этом каталоге библиотечных шагов должна быть одна фича с одним универсальным (параметризованным) шагом, который будет удалять документы.
4. В фичах поступления и продажи нужно использовать этот библиотечный шаг.

- [x] Фичи из воздуха
- [x] Детализация фичи
- [x] Создать свой шаг, проверяющий текст сообщения пользователю

**В дополнение к проверке навыка "Создать свой шаг, проверяющий текст предупреждения"**

Нужно реализовать свой шаг, используя функциональность "Автоматизированное тестирование 1С" и свойство "ТестовоПриложение" переменной "КонтекстСохраняемый", которое проверяет сообщения пользователю в момент проведения документа реализации товара. Например, если нет в сообщении текста "Не хватает товара", то реализация провелась корректно. Или если есть текст "Не хватает товара", а товара действительно нет на остатках, то - Ок, функциональность контроля остатков проверена.

**Программная работа с функциональностью "Автоматизированное тестирование 1С"**
- [x] Успешный прогон всех фич на чужом ПК

**Что нужно сделать**

1. Выгрузить конфигурацию в файлы (конфигуратор → конфигурация → выгрузить конфигурацию в файлы → <ИмяРепозиторияФинальногоЗадания>\src\cf);
2. Закоммитить и отправить во внешний репозиторий.

**Особенности**

* Приступать к выполнению этой задачи нужно после того, как закроете все созданные мной issue.
* В публичный внешний репозиторий нельзя помещать код из типовых конфигураций 1С!

**Comment by leemuar** [comment]
@madvlaydin я извиняюсь, но я не понял что нужно сделать.

Для чего в тексте issues чекбоксы?
Что значит "закроете все созданные мной issue"? Пока issue одна

**Comment by madvlaydin** [comment]
когда этот ишуз закрою и прогоню фичи, тогда ты получишь сертификат

**Comment by leemuar** [comment]
@madvlaydin спасибо, я тупой и не увидел в файлах курса ПДФник с финальным заданием

**Comment by madvlaydin** [comment]
![image](https://user-images.githubusercontent.com/25293179/31942783-2b527744-b8cf-11e7-83cd-655fe3c68c9e.png)
![image](https://user-images.githubusercontent.com/25293179/31942794-336b1f3a-b8cf-11e7-9d85-8f5f2f379bfb.png)
![image](https://user-images.githubusercontent.com/25293179/31942802-3a60e644-b8cf-11e7-9e18-b0c9dd37c295.png)

**Comment by leemuar** [comment]
Исправлено

**Comment by madvlaydin** [comment]
в 2 или 3 модуле автор курса говорит как пушить с привязкой к ишузу. Пересмотри и прими к сведению

фичи прошли

**Comment by leemuar** [comment]
@madvlaydin В коммитах, связанных с ишузами, есть привязка:

https://github.com/leemuar/silverb-devops1-final/issues/2
https://github.com/leemuar/silverb-devops1-final/issues/3

**Comment by madvlaydin** [comment]
Тимур, я все понимаю, но представь теперь себя на моем месте:
чтобы понять, что ты пушишь с привязкой к ишузам, я должен по твоему репозиторию поползать и посмотреть, хотя я сам создал тебе полный ишуз под номером 1.
в чем проблема комитить в него и в описании комита писать не абстрактное "выполнено", а закрыто такое-то требование или вроде того?

**Comment by leemuar** [comment]
@madvlaydin извини что доставляю тебе столько проблем. Видимо я не понял как будет проверяться задание на привязку: я искренне считал, что проверяться будет не просмотром дерева коммитов, а просмотром ишузов (в т.ч. закрытых). Такой вывод сделал на основании рассказанного в курсе: на каждую фичу делать ишуз, в коммитах упоминать конкретный ишуз, в ишузах можно увидеть относящиеся к ним коммиты.

При этом подумал, что упоминать "большой финальный ишуз" в коммитах не надо, только в ишузах конкретных фич.
